"""
30_fetch_pubmed_authors.py

Fetches full author lists, titles, journals, volumes, pages, and DOIs from PubMed
for all 28 corpus papers, then rebuilds references.bib with Vancouver-style entries.

Usage:
    python "30_fetch_pubmed_authors.py"

Requires: standard library only (urllib, xml.etree). No pip installs needed.

Output:
    overwrites data/references.bib
"""
import urllib.request
import urllib.parse
import xml.etree.ElementTree as ET
import time
import re
from pathlib import Path

# === Paths ===
BIB = Path(__file__).resolve().parent.parent / "data" / "references.bib"
BIB.parent.mkdir(parents=True, exist_ok=True)

# === All 28 corpus PMIDs in Order ===
PMIDS = [
    "41944974", "39412688", "41663975", "40605934", "34817635",
    "35583712", "35810561", "38061942", "38343220", "40386715",
    "39915711", "40217563", "40771387", "37495426", "38622546",
    "38796795", "38871552", "38939344", "39060962", "36879285",
    "37444526", "37832194", "35037985", "32941954", "40037925",
    "40371075", "40771372", "38223098",
]

# === Framework refs (unchanged; kept from current references.bib) ===
FRAMEWORK_BIB = """% =====================================================================
% references.bib -- auto-regenerated by 30_fetch_pubmed_authors.py
% Framework refs: author-year keys; corpus refs: pmid<PMID> keys.
% =====================================================================

@article{lambin2017,
  title   = {Radiomics: the bridge between medical imaging and personalized medicine},
  author  = {Lambin, Philippe and Leijenaar, Ralph T H and Deist, Timo M and Peerlings, Jurgen and de Jong, Evelyn E C and van Timmeren, Janna and Sanduleanu, Sebastian and Larue, Ruben T H M and Even, Aniek J G and Jochems, Arthur and others},
  journal = {Nature Reviews Clinical Oncology},
  volume  = {14},
  number  = {12},
  pages   = {749--762},
  year    = {2017}
}

@article{zwanenburg2020,
  title   = {The Image Biomarker Standardization Initiative: standardized quantitative radiomics for high-throughput image-based phenotyping},
  author  = {Zwanenburg, Alex and Valli{\\`e}res, Martin and Abdalah, Mahmoud A and Aerts, Hugo J W L and Andrearczyk, Vincent and Apte, Aditya and Ashrafinia, Saeed and Bakas, Spyridon and Beukinga, Roelof J and Boellaard, Ronald and others},
  journal = {Radiology},
  volume  = {295},
  number  = {2},
  pages   = {328--338},
  year    = {2020}
}

@article{mongan2020,
  title   = {Checklist for Artificial Intelligence in Medical Imaging (CLAIM): a guide for authors and reviewers},
  author  = {Mongan, John and Moy, Linda and Kahn, Charles E Jr},
  journal = {Radiology: Artificial Intelligence},
  volume  = {2},
  number  = {2},
  pages   = {e200029},
  year    = {2020}
}

@article{wolff2019,
  title   = {{PROBAST}: a tool to assess the risk of bias and applicability of prediction model studies},
  author  = {Wolff, Robert F and Moons, Karel G M and Riley, Richard D and Whiting, Penny F and Westwood, Marie and Collins, Gary S and Reitsma, Johannes B and Kleijnen, Jos and Mallett, Susan},
  journal = {Annals of Internal Medicine},
  volume  = {170},
  number  = {1},
  pages   = {51--58},
  year    = {2019}
}

@article{page2021,
  title   = {The {PRISMA} 2020 statement: an updated guideline for reporting systematic reviews},
  author  = {Page, Matthew J and McKenzie, Joanne E and Bossuyt, Patrick M and Boutron, Isabelle and Hoffmann, Tammy C and Mulrow, Cynthia D and Shamseer, Larissa and Tetzlaff, Jennifer M and Akl, Elie A and Brennan, Sue E and others},
  journal = {BMJ},
  volume  = {372},
  pages   = {n71},
  year    = {2021}
}

@article{zhang2024biomedclip,
  title   = {{BiomedCLIP}: a multimodal biomedical foundation model pretrained from fifteen million scientific image-text pairs},
  author  = {Zhang, Sheng and Xu, Yanbo and Usuyama, Naoto and Bagga, Hanwen and Tinn, Robert and Preston, Sam and Rao, Rajesh and Wei, Mu and Valluri, Naveen and Wong, Cliff and others},
  journal = {NEJM AI},
  volume  = {1},
  number  = {11},
  pages   = {AIoa2400640},
  year    = {2024}
}

@article{viechtbauer2010,
  title   = {Conducting meta-analyses in {R} with the metafor package},
  author  = {Viechtbauer, Wolfgang},
  journal = {Journal of Statistical Software},
  volume  = {36},
  number  = {3},
  pages   = {1--48},
  year    = {2010}
}

@article{hanley1982,
  title   = {The meaning and use of the area under a receiver operating characteristic (ROC) curve},
  author  = {Hanley, James A and McNeil, Barbara J},
  journal = {Radiology},
  volume  = {143},
  number  = {1},
  pages   = {29--36},
  year    = {1982}
}

@article{egger1997,
  title   = {Bias in meta-analysis detected by a simple, graphical test},
  author  = {Egger, Matthias and Davey Smith, George and Schneider, Martin and Minder, Christoph},
  journal = {BMJ},
  volume  = {315},
  number  = {7109},
  pages   = {629--634},
  year    = {1997}
}

@article{guyatt2008,
  title   = {{GRADE}: an emerging consensus on rating quality of evidence and strength of recommendations},
  author  = {Guyatt, Gordon H and Oxman, Andrew D and Vist, Gunn E and Kunz, Regina and Falck-Ytter, Yngve and Alonso-Coello, Pablo and Sch{\\"u}nemann, Holger J},
  journal = {BMJ},
  volume  = {336},
  number  = {7650},
  pages   = {924--926},
  year    = {2008}
}

@article{dersimonian1986,
  title   = {Meta-analysis in clinical trials},
  author  = {DerSimonian, Rebecca and Laird, Nan},
  journal = {Controlled Clinical Trials},
  volume  = {7},
  number  = {3},
  pages   = {177--188},
  year    = {1986}
}

"""

EUTILS = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"

def escape_bibtex(s):
    """Escape special BibTeX characters (basic)."""
    if not s:
        return ""
    # Protect existing { ... } braces minimally; escape % and #
    return s.replace("&", r"\&").replace("%", r"\%").replace("#", r"\#")

def fetch_pubmed(pmid):
    """Fetch a single PubMed record as XML and parse into a dict."""
    params = urllib.parse.urlencode({"db": "pubmed", "id": pmid, "retmode": "xml"})
    url = f"{EUTILS}?{params}"
    with urllib.request.urlopen(url, timeout=20) as r:
        xml_bytes = r.read()
    root = ET.fromstring(xml_bytes)
    art = root.find(".//PubmedArticle")
    if art is None:
        return None
    citation = art.find(".//MedlineCitation")
    article = citation.find(".//Article")
    rec = {"pmid": pmid}
    # Title
    t = article.find(".//ArticleTitle")
    rec["title"] = "".join(t.itertext()).strip() if t is not None else ""
    rec["title"] = rec["title"].rstrip(".")
    # Journal title
    j = article.find(".//Journal/Title")
    rec["journal"] = j.text.strip() if j is not None and j.text else ""
    # Year
    y = article.find(".//Journal/JournalIssue/PubDate/Year")
    if y is None:
        y = article.find(".//Journal/JournalIssue/PubDate/MedlineDate")
    rec["year"] = y.text.strip()[:4] if y is not None and y.text else ""
    # Volume + Issue
    v = article.find(".//Journal/JournalIssue/Volume")
    rec["volume"] = v.text.strip() if v is not None and v.text else ""
    n = article.find(".//Journal/JournalIssue/Issue")
    rec["number"] = n.text.strip() if n is not None and n.text else ""
    # Pages
    p = article.find(".//Pagination/MedlinePgn")
    rec["pages"] = p.text.strip() if p is not None and p.text else ""
    # DOI
    doi_elt = None
    for el in article.findall(".//ELocationID"):
        if el.attrib.get("EIdType") == "doi":
            doi_elt = el
            break
    rec["doi"] = doi_elt.text.strip() if doi_elt is not None and doi_elt.text else ""
    # Authors
    authors = []
    for a in article.findall(".//AuthorList/Author"):
        last = a.find("LastName")
        first = a.find("ForeName")
        if last is not None and last.text:
            ln = last.text.strip()
            if first is not None and first.text:
                # Convert "Iran C K" -> "Iran C K" (keep initials joined)
                fn = first.text.strip()
                authors.append(f"{ln}, {fn}")
            else:
                authors.append(ln)
        else:
            # Possibly a CollectiveName
            cn = a.find("CollectiveName")
            if cn is not None and cn.text:
                authors.append(cn.text.strip())
    rec["authors"] = authors
    return rec

def to_bibtex(rec):
    """Convert parsed record to a BibTeX entry."""
    pmid = rec["pmid"]
    title = escape_bibtex(rec["title"])
    authors_joined = " and ".join(rec["authors"])
    journal = escape_bibtex(rec["journal"])
    fields = [f"  title   = {{{title}}}",
              f"  author  = {{{authors_joined}}}",
              f"  journal = {{{journal}}}"]
    if rec["year"]:
        fields.append(f"  year    = {{{rec['year']}}}")
    if rec["volume"]:
        fields.append(f"  volume  = {{{rec['volume']}}}")
    if rec["number"]:
        fields.append(f"  number  = {{{rec['number']}}}")
    if rec["pages"]:
        fields.append(f"  pages   = {{{rec['pages']}}}")
    if rec["doi"]:
        fields.append(f"  doi     = {{{rec['doi']}}}")
    fields.append(f"  note    = {{PMID: {pmid}}}")
    body = ",\n".join(fields)
    return f"@article{{pmid{pmid},\n{body}\n}}\n"

def main():
    out_chunks = [FRAMEWORK_BIB, "% --- Corpus papers (auto-fetched from PubMed) ---\n\n"]
    print(f"Fetching {len(PMIDS)} PubMed records...")
    for i, pmid in enumerate(PMIDS, 1):
        print(f"  [{i:2d}/28] PMID {pmid}...", end=" ", flush=True)
        try:
            rec = fetch_pubmed(pmid)
            if rec is None:
                print("FAILED (no record)")
                continue
            out_chunks.append(to_bibtex(rec))
            out_chunks.append("\n")
            print(f"OK ({len(rec['authors'])} authors)")
        except Exception as e:
            print(f"ERROR: {e}")
        # NCBI: max 3 requests/sec without API key
        time.sleep(0.4)
    BIB.write_text("".join(out_chunks), encoding="utf-8")
    print()
    print(f"Wrote {BIB}")
    print(f"Size: {BIB.stat().st_size:,} bytes")

if __name__ == "__main__":
    main()
