r"""
32_table1_generator.py
Generate Table 1 (per-study characteristics) as a LaTeX longtable for the
systematic review manuscript.

Reads:
  - 12_Final_Included_Corpus.csv  (28 papers x 33 cols)
  - overleaf_project/references.bib (for first-author surname per PMID)

Writes:
  - overleaf_project/table1.tex   (\input-able file with landscape longtable)

Run on Windows:
    cd .
    python 32_table1_generator.py
"""
from pathlib import Path
import csv, io, re

ROOT = Path(__file__).resolve().parent.parent
CSV_PATH = ROOT / "data" / "12_Final_Included_Corpus.csv"
BIB_PATH = ROOT / "data" / "references.bib"
OUT_TEX  = ROOT / "outputs" / "table1.tex"

# ---------- Load corpus ----------
raw = CSV_PATH.read_bytes().decode("utf-8-sig").replace("\x00", "")
reader = csv.reader(io.StringIO(raw))
rows = list(reader)
header, data = rows[0], rows[1:]
col = {c: i for i, c in enumerate(header)}

# ---------- Parse references.bib to extract first-author surname per PMID ----------
bib_text = BIB_PATH.read_text(encoding="utf-8") if BIB_PATH.exists() else ""
pmid_to_author = {}
entries = re.split(r"\n@article\{", bib_text)
for ent in entries[1:]:
    m_key = re.match(r"(pmid\d+),", ent)
    if not m_key:
        continue
    pmid = m_key.group(1).replace("pmid", "")
    m_au = re.search(r"author\s*=\s*\{([^}]+)\}", ent)
    if m_au:
        first = m_au.group(1).split(" and ")[0].strip()
        surname = first.split(",")[0].strip() if "," in first else first.split()[-1]
        pmid_to_author[pmid] = surname
    else:
        pmid_to_author[pmid] = ""

# ---------- LaTeX escape ----------
def esc(s):
    if s is None:
        return ""
    s = str(s).strip()
    if not s or s.upper() == "NR":
        return "NR"
    s = (s.replace("\\", r"\textbackslash{}")
          .replace("&", r"\&")
          .replace("%", r"\%")
          .replace("$", r"\$")
          .replace("#", r"\#")
          .replace("_", r"\_")
          .replace("{", r"\{")
          .replace("}", r"\}")
          .replace("~", r"\textasciitilde{}")
          .replace("^", r"\textasciicircum{}")
          .replace("<", r"\textless{}")
          .replace(">", r"\textgreater{}"))
    return s

def short(s, n=22):
    """Pass-through. Truncation removed for the final-format pass — columns
    now use the L{} raggedright columntype so cells wrap naturally instead of
    overflowing. Function kept defined to avoid breaking older callers."""
    if not s:
        return ""
    return str(s).strip()

def parse_n(s):
    """Pull leading integer out of cohort cell."""
    if not s:
        return 0
    m = re.search(r"(\d+)", s.replace(",", ""))
    return int(m.group(1)) if m else 0

def delta_str(s):
    """Format Metric_Difference: ensure leading sign."""
    if not s or s.strip().upper() == "NR":
        return "NR"
    s = s.strip()
    if s.startswith(("+", "-")):
        return s
    try:
        v = float(s)
        return f"+{v:.3f}" if v >= 0 else f"{v:.3f}"
    except ValueError:
        return s

# ---------- Build per-row LaTeX ----------
lines = []
lines.append(r"% Table 1 -- generated by 32_table1_generator.py")
lines.append(r"% Place this file in the overleaf_project/ directory; include from main.tex with \input{table1}")
lines.append(r"")
lines.append(r"\clearpage")
lines.append(r"\begin{landscape}")
lines.append(r"\begin{footnotesize}")
lines.append(r"\setlength{\tabcolsep}{3pt}")
lines.append(r"\renewcommand{\arraystretch}{1.15}")
lines.append(r"")
lines.append(r"\sloppy")
# Column widths tuned 2026-05-20 (second iteration). Numeric value columns
# (FM, Rad, Delta) widened from 0.6cm to 0.8-0.9cm because +0.227 / -0.200
# are 6 characters and need ~1cm at footnotesize. Rad pkg and ML head
# restored to 1.7/1.9cm to fit ~33-char compound classifier strings.
# Anatomy and Modality tightened to compensate.
# Total: 19.4cm (within ~24.7cm landscape A4 textwidth with 3pt tabcolsep).
lines.append(r"\begin{longtable}{@{}L{0.4cm} L{2.4cm} L{1.4cm} L{2.3cm} L{0.7cm} L{0.5cm} L{2.0cm} L{2.3cm} L{1.7cm} L{1.9cm} L{0.7cm} L{0.8cm} L{0.8cm} L{0.9cm} L{0.5cm}@{}}")
lines.append(r"\caption{Per-study characteristics of the 28 included head-to-head foundation-model versus radiomics comparisons.}\label{tab:characteristics}\\")
lines.append(r"\toprule")
lines.append(r"\textbf{\#} & \textbf{Study} & \textbf{Modality} & \textbf{Anatomy} & \textbf{$n_{\text{tot}}$} & \textbf{Ext} & \textbf{FM model} & \textbf{FM pretraining} & \textbf{Rad pkg} & \textbf{ML head} & \textbf{Met} & \textbf{FM} & \textbf{Rad} & \textbf{$\Delta$} & \textbf{PB} \\")
lines.append(r"\midrule")
lines.append(r"\endfirsthead")
lines.append(r"\multicolumn{15}{c}{\emph{Table~\ref{tab:characteristics} continued from previous page}}\\")
lines.append(r"\toprule")
lines.append(r"\textbf{\#} & \textbf{Study} & \textbf{Modality} & \textbf{Anatomy} & \textbf{$n_{\text{tot}}$} & \textbf{Ext} & \textbf{FM model} & \textbf{FM pretraining} & \textbf{Rad pkg} & \textbf{ML head} & \textbf{Met} & \textbf{FM} & \textbf{Rad} & \textbf{$\Delta$} & \textbf{PB} \\")
lines.append(r"\midrule")
lines.append(r"\endhead")
lines.append(r"\midrule")
lines.append(r"\multicolumn{15}{r}{\emph{continued on next page}}\\")
lines.append(r"\endfoot")
lines.append(r"\bottomrule")
lines.append(r"\endlastfoot")

for r in data:
    if not r or not r[col["Order"]].strip():
        continue
    order  = r[col["Order"]].strip()
    pmid   = r[col["PMID"]].strip()
    year   = r[col["Year"]].strip()
    author = pmid_to_author.get(pmid, "")
    study  = f"{author} {year}" if author else f"PMID {pmid}"
    study_cite = f"\\cite{{pmid{pmid}}}" if pmid else ""

    modality = r[col["Modality"]].strip() or "NR"
    anatomy  = r[col["Anatomical_Region"]].strip()

    n_train = parse_n(r[col["Cohort_Train"]])
    n_int   = parse_n(r[col["Cohort_Internal_Test"]])
    n_ext   = parse_n(r[col["Cohort_External_Test"]])
    n_tot   = n_train + n_int + n_ext
    n_tot_s = f"{n_tot:,}" if n_tot > 0 else "NR"

    ext = r[col["External_Validation"]].strip().upper()
    ext_s = "Y" if ext.startswith("Y") else ("N" if ext.startswith("N") else "?")

    fm_model   = r[col["FM_Name"]].strip()
    # Replace unbreakable-underscore variant suffixes with shorter aliases so
    # the cell wraps cleanly (row 23 "ResNeXt101_32x8d" -> "ResNeXt-101").
    if "ResNeXt101_32x8d" in fm_model:
        fm_model = "ResNeXt-101"
    fm_pretrain = r[col["FM_Pretraining"]].strip()
    rad_pkg    = r[col["Radiomics_Package"]].strip()
    ml_head    = r[col["ML_Head"]].strip()

    fm_metric = r[col["FM_Arm_Metric"]].strip() or "AUC"
    fm_val    = r[col["FM_Arm_Value"]].strip()
    rad_val   = r[col["Rad_Arm_Value"]].strip()
    delta     = delta_str(r[col["Metric_Difference"]])
    probast   = r[col["PROBAST_Rating"]].strip() or "?"
    pb_short  = {"High": "H", "Unclear": "U", "Low": "L"}.get(probast, "?")

    cells = [
        order,
        f"{esc(study)} {study_cite}",
        esc(short(modality, 18)),
        esc(short(anatomy, 26)),
        n_tot_s,
        ext_s,
        esc(short(fm_model, 22)),
        esc(short(fm_pretrain, 22)),
        esc(short(rad_pkg, 18)),
        esc(short(ml_head, 14)),
        esc(short(fm_metric, 6)),
        esc(fm_val[:5]) if fm_val else "NR",
        esc(rad_val[:5]) if rad_val else "NR",
        esc(delta),
        pb_short,
    ]
    lines.append(" & ".join(cells) + r" \\")

lines.append(r"")
lines.append(r"\end{longtable}")
lines.append(r"\end{footnotesize}")
lines.append(r"